Code/home/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.homepage),
    path('aportaciones',views.pagina_aportaciones),
    path('info',views.pagina_info),
     path('user/<str:llave>',views.pagina_usuario),
    path('<str:llave>',views.pagina_recurso),

]

Code/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView as login

urlpatterns = [
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('login/',login.as_view())

]

Code/home/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    TOPICS=[
        ('AE','aemet'),
        ('WI','wikipedia'),
        ('YU','youtube'),
        ('RE','reddit'),
        ('NR','other'),
    ]
    topic=models.CharField(max_length=2, choices=TOPICS)
    def __str__(self):
       return str(self.id)+":"+self.topic

class Content(models.Model):
    clave = models.CharField(max_length=64)
    valor = models.TextField()
    user = models.TextField()
    votos_pos=models.IntegerField()
    votos_neg=models.IntegerField()
    date = models.DateTimeField('published')
    Ncoments=models.IntegerField()
    topic=models.ManyToManyField(Topic)
    def __str__(self):
       return self.clave+":"+self.valor


class Comentario(models.Model):
    content = models.ForeignKey(Content,on_delete=models.CASCADE)
    valor = models.TextField()
    title =models.CharField(max_length=200)
    date = models.DateTimeField('published')
    user = models.TextField()
    def __str__(self):
        return self.title + ":" + self.valor

class Voto(models.Model):
    content = models.ForeignKey(Content,on_delete=models.CASCADE)
    user = models.TextField()
    valor = models.TextField()
    def __str__(self):
       return str(self.content)+":"+self.user

Code/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.template import loader
from django.contrib.auth import logout
from django.shortcuts import redirect, render
from . import models
from .models import Content, Comentario, Voto
from django.utils import timezone
from django.http import HttpResponse
from bs4 import BeautifulSoup
import requests
import unicodedata
from urllib.request import urlopen
from requests_html import HTMLSession
@csrf_exempt
def pagina_recurso(request,llave):
    if request.method =="PUT":
        valor = request.body.decode('utf-8')
    if request.method =="POST":
        if request.POST['action'] == "Cambiar contenido":
            try:
                c= Content.objects.get(clave=llave)
                c.objects.valor=request.POST['valor']
                c.save()
            except Content.DoesNotExist:
                c=Content(clave=llave, valor=request.POST['valor'])
                c.save()
        elif request.POST['action']== "Enviar contenido":
            clave = llave
            try:
                c= Content.objects.get(clave=clave)
                c.delete()
            except Content.DoesNotExist:
             pass
            c=Content(clave=clave, valor=request.POST['valor'],
                          user=request.user.username,
                          votos_pos=0,
                          votos_neg=0,
                          Ncoments=0,
                          date=timezone.now())
            c.save()

        elif request.POST['action']== "LIKE":
            contenido = Content.objects.get(clave=llave)
            contenido.votos_pos= contenido.votos_pos+1
            contenido.save()
            votoaux=Voto(content=Content.objects.get(clave=llave),
                         user=request.user.username,
                        valor="like")
            votoaux.save()
        elif request.POST['action']== "Iniciar sesion":
            return redirect('login/')
        elif request.POST['action']== "Cerrar sesion":
            logout(request)
            return redirect('/')
        elif request.POST['action']== "HATE":
            contenido= Content.objects.get(clave=llave)
            contenido.votos_neg= contenido.votos_neg+1
            contenido.save()
            votoaux = Voto(content=Content.objects.get(clave=llave),
                           user=request.user.username,
                           valor="hate")
            votoaux.save()
        elif request.POST['action']== "Borrar contenido":
            try:
                c= Content.objects.get(clave=llave)
                c.delete()
                return redirect('/')
            except Content.DoesNotExist:
                c=Content.objects.get(clave=llave, valor = valor)
                c.save()
        elif request.POST['action']== "Pagina de inicio":
            return redirect('/')

        elif request.POST['action']== "Area personal":
            return redirect('/user/<request.user.username>')
        elif request.POST['action']== "Resumen aportaciones":
            return redirect('/aportaciones')
        elif request.POST['action']== "Informacion":
            return redirect('/info')
        elif request.POST['action']== "borrar votacion":
            contenido= Content.objects.get(clave=llave)
            votoaux = Voto.objects.get(content=Content.objects.get(clave=llave),
                           user=request.user.username)

            if votoaux.valor=="like":
                contenido.votos_pos= contenido.votos_pos-1
            elif votoaux.valor=="hate":
                contenido.votos_neg= contenido.votos_neg-1
            contenido.save()
            votoaux.delete()
        elif request.POST['action']== "Enviar comentario":
            contenido = Content.objects.get(clave=llave)
            contenido.Ncoments= contenido.Ncoments+1
            q=Comentario(content=contenido, title=request.POST['titulo'],
                         valor=request.POST['valor'],
                         date=timezone.now(),
                         user=request.user.username)
            q.save()
            contenido.save()
    try:
        content=Content.objects.get(clave=llave)
        context={"content":content}
    except Content.DoesNotExist:
            context={}
            return render(request, 'home/notfoundcontent.html', context)
    content = Content.objects.get(clave=llave)
    coment_list = (Comentario.objects.all())
    vote_list = Voto.objects.all()
    context = {
         'content': content,
         'coment_list': coment_list,
         'vote_list':vote_list
     }
    content = Content.objects.get(clave=llave)
    url = content.valor
    # Headers to mimic a browser visit
    headers = {'User-Agent': 'Mozilla/5.0'}
    # Returns a requests.models.Response object
    try:
        page = requests.get(url, headers=headers)
        soup = BeautifulSoup(page.text, 'html.parser')

        if "www.reddit.com" in url:
            try:
                text = soup.find("p", class_="_1qeIAgB0cPwnLhDF9XSiJM").text
                aprobacion=soup.find("div", class_="t4Hq30BDzTeJ85vREX7_M").text
                title = soup.find("title").text
                context = {
                     'content': content,
                     'coment_list': coment_list,
                     'vote_list':vote_list,
                    'texto':text,
                    'title':title,
                    'aprob':aprobacion
                 }
                return render(request,'home/paginareddit.html', context)
            except AttributeError:
                  context = {
                     'content': content,
                     'coment_list': coment_list,
                     'vote_list':vote_list
                  }
            return render(request,'home/paginarecursoerror.html', context)
        elif "es.wikipedia.org" in url:
            try:
                images=soup.findAll('img')
                title = soup.find(id="firstHeading").text
                imagen=((images[0])['src'])
                context = {
                     'content': content,
                     'coment_list': coment_list,
                     'vote_list':vote_list,
                        'title':title,
                   # 'texto':text,
                    'imagen':imagen,
                    #'copy':copy
                 }
                return render(request,'home/paginawiki.html', context)
            except AttributeError:
                  context = {
                     'content': content,
                     'coment_list': coment_list,
                     'vote_list':vote_list }
            return render(request,'home/paginarecursoerror.html', context)
        elif "www.aemet.es" in url:
            try:
                title = soup.find("title").text
                temp12 = soup.find("div", class_="no_wrap").text
                fecha12 = soup.find("th", class_="borde_izq_dcha_fecha").text
                maxymin = soup.find("td", class_="alinear_texto_centro no_wrap comunes").text
                precipitacion = soup.find("td", class_="nocomunes").text
                context = {
                     'content': content,
                     'coment_list': coment_list,
                     'vote_list':vote_list,
                        'title':title,
                        'temp12':temp12,
                        'fecha12':fecha12,
                        'maxymin':maxymin,
                        'precipitacion':precipitacion
                   # 'texto':text,
                    #'imagen':imagen,
                    #'copy':copy
                 }
                return render(request,'home/paginaAEMET.html', context)
            except AttributeError:
                  context = {
                     'content': content,
                     'coment_list': coment_list,
                     'vote_list':vote_list }
            return render(request,'home/paginarecursoerror.html', context)
        elif "www.youtube.com" in url:
            try:
                print(soup)
                title = soup.find("span", class_="watch-title").text.replace("\n", "")
                views = soup.find("div", class_="watch-view-count").text
                likes = soup.find("span", class_="like-button-renderer").span.button.text
                print(title)
                print(views)
                print(likes)
                context = {
                     'content': content,
                     'coment_list': coment_list,
                     'vote_list':vote_list,

                 }
                return render(request,'home/paginayoutube.html', context)
            except AttributeError:
                  context = {
                     'content': content,
                     'coment_list': coment_list,
                     'vote_list':vote_list }
            return render(request,'home/paginarecursoerror.html', context)
        else:
            try:
                images=soup.findAll('img')
                title = soup.find("title").text
                imagen=((images[0])['src'])
                context = {
                     'content': content,
                     'coment_list': coment_list,
                     'vote_list':vote_list,
                        'title':title,
                      'img':img
                     }
                return render(request,'home/paginarecursonorec.html', context)
            except AttributeError:
                  context = {
                     'content': content,
                     'coment_list': coment_list,
                     'vote_list':vote_list }
            return render(request,'home/paginarecursoerror.html', context)
    except:
        context = {
                     'content': content,
                     'coment_list': coment_list,
                     'vote_list':vote_list }
    return render(request,'home/paginarecursoerror.html', context)

Code/templates/home/homepage.html
{% extends 'home/schema.html' %}
{%block cuerpo%}
    {%if content_list_crop%}
    <h1>
        Pagina principal de LoVisto2021 de jorgemartinezalmeida, en esta pagina podras encontrar
        una red social.En esta podras subir enlaces que te resulten interesantes, ya que mas gente
        podria estar interesada tambien puede comentar y puntuar las publicaciones que otras personas
        hayan subido.
    </h1>
           {%for content in content_list_crop%}
<br><br>
                      <table style="width:auto" align="rigth">
                        <th><a href="/{{content.clave}}">{{content.clave}}</a></th>
                        <tr>
                            <td>el valor del valor  es:</td>
                            <td>{{ content.valor }}</td>
                        </tr>
                        <tr>
                           <td>votos positivos : </td>
                            <td>{{ content.votos_pos }}</td>
                        </tr>
                        <tr>
                            <td>votos negativos : </td>
                            <td>{{ content.votos_neg }}</td>
                        </tr>
                        <tr>
                            <td>fecha de publicacion : </td>
                             <td>{{ content.date }}</td>
                        </tr>
                          <tr>
                            <td>Publicado por : </td>
                             <td>{{ content.user }}</td>
                        </tr>
                        <tr>
                            <td>numero de comentarios : </td>
                            <td>{{ content.Ncoments }}</td>
                        </tr>
                     </table>
               </td>
            </tr>
        {%endfor%}
    {%else%}
        <p>No tenemos contenidos que mostrar</p>
    {%endif%}

{% endblock %}
{%block lateral%}
    {%  if request.user.is_authenticated%}
        <br>
        <p>Introduce nuevo contenido<p>
        <form action="" method ="POST">
             {% csrf_token %}
            <table style="width:auto" align="left">
               <tr>
                   <td>Titulo:</td>
                   <td><input type="text" name="clave"></td>
               </tr>
                <tr>
                     <td>Cuerpo:</td>
                     <td><input type="text" name="valor"></td>
                </tr>
            </table>
    <input class="boton_personalizado" type="submit" name="action" value="nuevo contenido">
        </form>
  {% else %}
    <br><br>

    <p>Para poder introducir un contenido necesitas estar autenticado</p>
    {%endif%}
{% if request.user.is_authenticated%}
        {%if content_list%}
<br><br>
            Aportaciones del usuario
             {%for content in content_list%}
<br>
                 {% ifequal content.user request.user.username %}
                        <a href="/{{content.clave}}">{{content.clave}}</a>
                 {%endifequal%}
            {%endfor%}
             <br>

        {%endif%}
  {%endif%}
<br><br><br><br>
<p>Previsualizacion de <a href="https://www.urjc.es/etsit">Pagina Etsit</a></p>
            <iframe src="https://www.urjc.es/etsit" height="400" width="65%" name="demo">
             <p>Su navegador no es compatible con iframes</p>
            </iframe>
{% endblock %}

Code/templates/home/notfoundcontent.html
{% extends 'home/schema.html' %}
{%block cuerpo%}
    {%  if request.user.is_authenticated%}
            Este contenido no exixte, lo puedes añadir
        <table style="width:auto" align="center">
            <form action="" method ="POST">
                {% csrf_token %}
               <tr>
                    <td><br>Cuerpo: </td>
                     <td><input type="text" name="valor"></td>
               </tr>
                <tr>
                     <td><br/><input class="boton_personalizado" type="submit" name="action" value="Enviar contenido"></td>
                </tr>
            </form>
         </table>
    {% else %}
         <p>Para poder añadir un comentario necesitas estar autenticado<p/>
    {%endif%}
{%endblock%}
{%block lateral%}
<form action="" method ="POST">
            {% csrf_token %}
        <br/><input class="boton_personalizado"type="submit" name="action" value="gohome">
    </form>
{%endblock%}

Code/templates/home/paginaAEMET.html
{% extends 'home/paginarecurso.html' %}
{%block aportacion%}
<div class="aemet">
<p>{{title}}</p>
<ul>
    <li>Dia:{{fecha12}}.</li>
    <li> Temperatura 12-18h: {{temp12}}</li>
    <li>Temperatura mínima y máxima (°C):{{maxymin}}</li>
    <li>Probabilidad de precipitación:{{precipitacion}}</li>
</ul>
<p>© AEMET. Autorizado el uso de la información y su reproducción citando a AEMET como autora de la misma.
<br>
    <a href={{content.valor}}>Página
original en AEMET</a></p>
</div>
</div>
{%endblock%}

Code/templates/home/paginainfo.html
{% extends 'home/schema.html' %}
{%block cuerpo%}
<p>
  En esta pagina se encuentra la informacion de la practica,<br>
  su autoria y un poco de documentacion
<p/>
<p>
  Soy Jorge Martinez-Almeida Ramos, he usado la herramienta <br>
    Django 3.0.3, utilizando Python 3.8.5. Como Ide para la <br>
    implementacion he usadoPyCharm 2021.1.2 (Community Edition).<br>
    Implementado en un sistema Ubuntu 20.04.2 LTS
<p/>
<p>Para el Web scraping se han utilizado varias librerias externas estas son:
   <br> from bs4 import BeautifulSoup
    <br>import requests
    <br>import unicodedata
    <br>from urllib.request import urlopen
    <br>from requests_html import HTMLSession
<p/>
<p>
  Debido a problemas de tiempo falta/organizacion no he podido implementar  el web
  scraping para las paginas de youtube, ya que la url siempre me solicitaba loggearme
  para poder ver el html directamente.Tambien me ha faltado dar la opcion de descargar
  el documento html o json de una pagina.
</p>
 <p>
   Contenido adicional:
   <br>Implementacion de un iframe con la pagina de cada recurso
   <br>Implementacion de un iframe con la pagina de la escuela
   I<br>mplementacion de unfavicon
<p/>
{% endblock %}
{%block lateral%}
<br><br>
<a href="https://www.urjc.es/etsit">Pagina Etsit</a></p>
            <iframe src="https://www.urjc.es/etsit" height="400" width="65%" name="demo">
             <p>Su navegador no es compatible con iframes</p>
            </iframe>
{% endblock %}

Code/templates/home/paginarecurso.html
{% extends 'home/schema.html' %}
{%block cuerpo%}
        <tr>
           <td>
                <table style="width:auto" align="center">
                    <th><a href="/{{content.clave}}">{{content.clave}}</a></th>
                    <tr>
                        <td>el valor del valor  es:</td>
                        <td>{{ content.valor }}</td>
                    </tr>
                    <tr>
                       <td>votos positivos : </td>
                        <td>{{ content.votos_pos }}</td>
                    </tr>
                    <tr>
                        <td>votos negativos : </td>
                        <td>{{ content.votos_neg }}</td>
                    </tr>
                    <tr>
                        <td>fecha de publicacion : </td>
                         <td>{{ content.date }}</td>
                    </tr>
                    <tr>
                        <td>numero de comentarios : </td>
                        <td>{{ content.Ncoments }}</td>
                    </tr>
                 </table>

           </td>
        </tr>

     {%if request.user.is_authenticated%}
        {%if content.voto_set.all%}
            {% for voto in content.voto_set.all%}
                     {%ifequal voto.user request.user.username %}
                       <br> Ya ha votado {{voto.valor}}
                        <form action="" method ="POST">
                                {% csrf_token %}
                             <td><input class="boton_personalizado" type="submit" name="action" value="borrar votacion"></td>
                           </tr>
                        </form>
                    {%else%}
                    <br><br>
                    <table style="width:auto" align="left">
                        <form action="" method ="POST">
                                {% csrf_token %}
                            <tr> <td><input class="boton_personalizado" type="submit" name="action" value="LIKE"></td>
                        </form>
                        <form action="" method ="POST">
                                {% csrf_token %}
                             <td><input class="boton_personalizado" type="submit" name="action" value="HATE"></td>
                           </tr>
                        </form>
                        </table>
                        <br><br><br>
                    {%endifequal%}
             {%endfor%}
        {%else%}
        <br>
        <table style="width:auto" align="center">
                        <form action="" method ="POST">
                                {% csrf_token %}
                            <tr> <td><input class="boton_personalizado" type="submit" name="action" value="LIKE"></td>
                        </form>
                        <form action="" method ="POST">
                                {% csrf_token %}
                             <td><input class="boton_personalizado" type="submit" name="action" value="HATE"></td>
                           </tr>
                        </form>
                        </table>

                        <br><br>
    {%endif%}
{%endif%}
{%block aportacion%}

{%endblock%}
<br><br>
    <p>Comentarios</p>
        {% for comentario in content.comentario_set.all%}
            <br>
            <table style="width:auto" align="center">
                        <tr>
                               <td><b>Titulo:<b/></td>
                               <td>{{comentario.title }}</td>
                        </tr>
                        <tr>
                            <td><b>Cuerpo:<b/></td>
                               <td> {{comentario.valor }}</td>
                        </tr>
                <tr>
                            <td><b>Usuario:<b/></td>
                               <td> {{comentario.user }}</td>
                        </tr>
                        <tr>
                            <td><b>Fecha:<b/></td>
                            <td>{{ comentario.date }}</td>
                        </tr>
            </table>
        {%endfor%}
 <br><br>
    <p>Votos</p>
        {% for voto in content.voto_set.all%}
            <br>
            <table style="width:auto" align="center">
                        <tr>
                               <td><b>usuario:<b/></td>
                               <td>{{voto.user }}</td>
                        </tr>
                        <tr>
                            <td><b>Cuerpo:<b/></td>
                               <td> {{voto.valor }}</td>
                        </tr>
            </table>
        {%endfor%}
    <br>

{%endblock%}
{%block lateral%}
{%if request.user.is_authenticated%}
    <p>Introduce nuevo comentario</p>
            <form action="" method ="POST">
                <table style="width:auto" align="left">
                    {% csrf_token %}
                       <tr>
                           <td>Titulo:</td>
                           <td> <input type="text" name="titulo"></td>
                        </tr>
                        <tr>
                           <td> <br>Cuerpo:</td>
                           <td> <input type="text" name="valor"></td>
                        </tr>
            </table> <br> <br> <br>
                    <br/><input class="boton_personalizado"  type="submit" name="action" value="Enviar comentario">
                </form>
{% else%}
    <p>Para poder comentar en una publicacion tienes que haber iniciado sesion</p>
{%endif%}
<br>
    {%ifequal  request.user.username  content.user  %}
     <p>Edita el contenido</p>
        <form action="" method ="POST">
            <table style="width:auto" align="left">
                    {% csrf_token %}
                <tr>
                   <td> Nuevo cuerpo: </td>
                    <td><input type="text" name="valor"></td>
                </tr>
            </table>
            <br> <br>
            <input class="boton_personalizado" type="submit" name="action" value="Cambiar contenido">
        </form>
<br>
         <p>Borrar contenido</p>
        <form action="" method ="POST">
                {% csrf_token %}
            <input class="boton_personalizado"type="submit" name="action" value="Borrar contenido">
        </form>
        {%else%}
            <br><br><p>Solo {{ content.user }} puede editar esta publicacion</p>
        {%endifequal%}
    <br><br>
     <p>Previsualizacion de <a href={{content.valor}}>Pagina recurso</a></p>
   <iframe src="{{ content.valor }}" height="400" width="65%" name="demo">
      <p>Su navegador no es compatible con iframes</p>
    </iframe>
    <br><br>
 <p>Previsualizacion de <a href="https://www.urjc.es/etsit">Pagina Etsit</a></p>
            <iframe src="https://www.urjc.es/etsit" height="400" width="65%" name="demo">
             <p>Su navegador no es compatible con iframes</p>
            </iframe>
{%endblock%}

Code/templates/home/paginarecursoerror.html
{% extends 'home/paginarecurso.html' %}
{%block aportacion%}
No se puede extraer mas informacion de la pagina solicitada
{%endblock%}

Code/templates/home/paginarecursonorec.html
<div class="og">
<p>Este es el titulo</p>
<img src="https://..../imagen.jpg">
</div>

{% extends 'home/paginarecurso.html' %}
{%block aportacion%}
<div class="og">
  <p>Recurso no reconocido en nuestra plataforma, hemos podido extraer esta informacion</p>
  <p>Este es el titulo:{{title}}</p>
  <img src={{img}}>
  </div>

  <a href={{content.valor}}>Artículo
  original</a>.</p>
</div>
</div>
{%endblock%}

Code/templates/home/paginareddit.html
{% extends 'home/paginarecurso.html' %}
{%block aportacion%}
<div class="reddit">
<p>Nota Reddit: {{title}}</p>
<p>{{texto}}</p>
<p><a href="https://www.reddit.com/r/django/comments/n842st">Publicado
en [subreddit]</a>. Aprobación: {{aprob}}.</p>
</div>
{%endblock%}

Code/templates/home/paginatodasaporrtaciones.html
{% extends 'home/schema.html' %}
{%block cuerpo%}
    {%if content_list%}
    <h1>
        En esta pagina podra encontrar la lista
        <br>de todas las aportaciones que hemos recibido.
        <br>Ordenadas de recientes a mas antiguas<br>
    </h1>
    <table style="width:auto" align="center">
           {%for content in content_list%}

            <tr>
               <td>
                   <a href="{{content.clave}}">{{content.clave}}</a>

               </td>
            </tr>
        {%endfor%}
   </table>
    {%else%}
        <p>No tenemos contenidos que mostrar</p>
    {%endif%}
{% endblock %}
{%block lateral%}
<br><br>
<a href="https://www.urjc.es/etsit">Pagina Etsit</a></p>
            <iframe src="https://www.urjc.es/etsit" height="400" width="65%" name="demo">
             <p>Su navegador no es compatible con iframes</p>
            </iframe>
{% endblock %}

Code/templates/home/paginawiki.html
{% extends 'home/paginarecurso.html' %}
{%block aportacion%}
<div class="wikipedia">
  <p>Artıculo Wikipedia: {{title}}</p>
  <img src={{imagen}}>
  <p>El texto está disponible bajo la Licencia Creative Commons Atribución Compartir Igual 3.0; pueden aplicarse cláusulas adicionales. Al usar este sitio, usted acepta nuestros términos de uso y nuestra política de privacidad.
Wikipedia® es una marca registrada de la Fundación Wikimedia, Inc., una organización sin ánimo de lucro.
  <a href={{content.valor}}>Artículo
  original</a>.</p>
</div>
</div>
{%endblock%}

Code/templates/home/paginayoutube.html
{% extends 'home/paginarecurso.html' %}
{%block aportacion%}
<div class="youtube">
<p>Video YouTube: Presentaci´on de la asignatura</p>
<iframe width="560" height="315"
src="https://www.youtube.com/embed/IfoSqaxJsAM"
title="YouTube video player" frameborder="0"
allow="accelerometer; encrypted-media; gyroscope; picture-in-picture"
allowfullscreen>
</iframe>
<p>Autor: CursosWeb.
<a href="https://www.youtube.com/watch?v=IfoSqaxJsAM">Video
en YouTube</a></p>
</div>
{%endblock%}

Code/templates/home/reconocido.html
{% extends 'home/paginarecurso.html' %}
{%block recursoreconocido%}
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/EMetY68NoUU"
        title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen>
</iframe>
{%endblock%}